---
- hosts: all
  become: yes
  vars_files:
    - /etc/ansible/credentials.yaml
  tasks:
   - name: Download a WAR File to the Tomcat webapps directory to be deployed
     maven_artifact:
       group_id: com.devops4solutions
       artifact_id: LoginWebApp
       version: "{{ ArtifactVersion }}"
       #extension: war
       repository_url: 'http://3.110.168.221:8081/repository/maven-releases/'
       username: "{{ username }}"
       password: "{{ password }}"
       dest: /opt/apache-tomcat-9.0.67/webapps
       
