---
- hosts: all
  become: yes
  tasks:
   - name: Download a WAR File to the Tomcat webapps directory to be deployed
     maven_artifact:
       group_id: com.devops4solutions
       artifact_id: LoginWebApp
       extension: war
       repository_url: 'http://3.83.158.14:8081/repository/maven-releases/'
       username: admin
       password: admin
       dest: /opt/apache-tomcat-9.0.65/webapps/
